language: erlang

env:
#   - ST=Pharo-1.4    # Issue #41
#   - ST=PharoCore-1.3
   - ST=Squeak-4.3
   - ST=Squeak-4.4

# blacklist
branches:
  except:
    - master

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $BUILDER_CI_HOME/testTravisCI.sh
