language: erlang

env:
   - ST=PharoCore-1.1

# blacklist
branches:
  except:
    - master
    - pharo1.1 # until builderCI supports PharoCore-1.1.2

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script:

   - ./build.sh -i $ST -m -f "$PROJECT_HOME/tests/travisCI.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - $BUILDER_CI_HOME/buildImageErrorCheck.sh
   - $BUILDER_CI_HOME/buildTravisStatusCheck.sh
